{% set xorg_name = "libxshmfence" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.3.3" %}
{% set sha256 = "6233ccd9fa80198835efc3039cdf8086ab2b218b17e77ebdb0a19913fcee58d3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - windows.patch  # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - m2-autoconf                  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool                   # [win]
    - pkg-config                   # [unix]
    - m2-pkg-config                # [win]
    - gnuconfig                    # [unix]
    - m2-base                      # [win]
    - make                         # [unix]
    - m2-make                      # [win]
    - {{ compiler("c") }}          # [unix]
    - {{ compiler("m2w64_c") }}    # [win]
    - autoconf                     # [unix]
    - automake                     # [unix]
    - gettext                      # [unix]
    - libtool                      # [unix]
  host:
    - pthread-stubs
    - xorg-xorgproto
    - xorg-util-macros

test:
  commands:
    - echo on  # [win]
    {% set lib_idents = [ "xshmfence" ] %}
    {% for lib_ident in lib_idents %}
    - test -f $PREFIX/lib/lib{{ lib_ident }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ lib_ident }}.so     # [linux]
    - if not exist %LIBRARY_BIN%\msys-{{ lib_ident }}-1.dll exit /b 1    # [win]
    - if not exist %LIBRARY_INC%\X11\{{ lib_ident }}.h exit /b 1         # [win]
    - if not exist %LIBRARY_LIB%\lib{{ lib_ident }}.dll.a exit /b 1      # [win]
    - if not exist %LIBRARY_LIB%\pkgconfig\{{ lib_ident }}.pc exit /b 1  # [win]
    {% endfor %}

about:
  home: https://www.x.org/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxshmfence
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libxshmfence
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Shared memory 'SyncFence' synchronization primitive

extra:
  recipe-maintainers:
    - ehfd
